version: "3.9"
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "tacyproject"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d tacyproject" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
        resources:
          limits:
            cpus: '1'
            memory: 4G
    ports:
      - "5432:5432"
